terraform/base/main.tf
terraform/ecr/main.tf
terraform/gitlab/kubefirst-repos.tf
terraform/vault/bootstrap/k8s-auth-backend.tf
terraform/vault/bootstrap/secrets.tf
terraform/vault/bootstrap/variables.tf
terraform/vault/main.tf
terraform/vault/variables.tf

With this PR we persist on Vault the token used on webhook configuration in the GitHub repository and use on secret inject in Atlantis.
PLUS: added default tag to ensure that all resources have the tag cluster_name.
Related with: https://github.com/kubefirst/kubefirst/pull/433 and also close https://github.com/kubefirst/kubefirst/issues/398

Add gh webhook secret of atlantis

---

components/github-runner/github-runner.yaml

this adjustment is needed to prevent argocd from endlessly cycling between our desired [] and the actual empty element that results from applying this config. unsetting it causes the app to cleanly sync and not thrash.

stop actions-runner-controller thrashing

---

localhost/components/development/metaphor-frontend/values.yaml
localhost/components/production/metaphor-frontend/values.yaml
localhost/components/staging/metaphor-frontend/values.yaml
localhost/registry/development.yaml

this changeset will adjust the local experience such that the development environment will be enabled by default.
this will also provide the appropriate override values for frontend to reach the backend api over the expected port forwards.

enable development by default and fix metaphor frontend

---

components/argo-cwfts/cwft-docker.yaml
components/argo-cwfts/cwft-git.yaml
components/argo-cwfts/cwft-helm.yaml
components/argo-cwfts/cwft-npm.yaml
components/atlantis/application.yaml
components/external-secrets-store/vault-cluster-secret-store-secret.yaml
components/kubefirst/vouch.yaml
components/vault/vault-unseal.yaml
registry/external-dns.yaml
terraform/base/eks/main.tf
terraform/base/eks/variables.tf
terraform/base/main.tf
terraform/base/variables.tf

To achieve support on graviton compute nodes in aws eks, this pr change some resources:
terraform to accept variables instance_type and ami_types to change computes nodes to have graviton;
some helm charts, or overwrite docker images to support graviton/arm on aws eks compute nodes;
Related: https://github.com/kubefirst/kubefirst/pull/702

eks graviton support

---

terraform/vault/oidc-provider.tf

this is duplicative to the required providers in `gitops-template/terraform/vault/main.tf`

remove duplicate required providers

---

localhost/terraform/users/modules/user/github/main.tf
localhost/terraform/users/modules/user/gitlab/main.tf
localhost/terraform/users/providers.tf
localhost/terraform/vault/main.tf

- Supports self-signed certs on VAULT terraform calls
- To allow support of `mkcert -install` becoming optional on local

Vault local - Skip Verify

---

terraform/base/dynamodb/vault.tf
terraform/base/eks/main.tf
terraform/base/kms/main.tf
terraform/base/main.tf
terraform/gitlab/kubefirst-repos.tf
terraform/vault/k8s-auth-backend.tf

with this PR we normalize the use of tags on tf resources to use tags on provider resources (default tags) instead of tags on each tf resource;
so we can centralize future changes and stop the fight between individual tags and default tags making noise changes during atlantis plan/apply;

change internal tags to use provider default tags

---

terraform/base/eks/variables.tf
terraform/vault/secrets-github.tf
terraform/vault/variables.tf

Persisting tf vars which values are changed by k1 flag in Atlantis secrets to solving the unexpected behavior of Atlantis plan/apply changing resources using default values.
Close:
- https://github.com/kubefirst/kubefirst/issues/809

fix #809 - vars persisted on vault to atlantis

---

localhost/components/minio/application.yaml
localhost/components/minio/pvc.yaml

The new PVC will be used for minio backend to write on disk instead memory.
Signed-off-by: Jessica Marinho <jessica@kubeshop.io>

feat: include persistence to minio on localhost

---

civo-github/mgmt-cluster-template/cluster-secret-store.yaml
civo-github/mgmt-cluster-template/components/atlantis/application.yaml
civo-github/mgmt-cluster-template/components/cluster-secret-store/clustersecretstore.yaml
civo-github/mgmt-cluster-template/components/external-secrets-operator/external-secrets-operator.yaml
civo-github/mgmt-cluster-template/components/vault/application.yaml
civo-github/terraform/civo/main.tf
civo-github/terraform/vault/kubernetes-auth-backend.tf
civo-github/terraform/vault/main.tf
civo-github/terraform/vault/variables.tf

- Uses kubenernetes auth for vault instead of depending on a token
- Create kubeconfig in cluster as a secret so it can be referenced in later steps

enhancement: Changes to Civo Vault

---

aws-github/.kubefirst/clusters/mgmt-template/components/github-runner/runnerdeployment.yaml
civo-github/mgmt-cluster-template/components/github-runner/runnerdeployment.yaml

Move away from using repository-scoped runners for cloud deployments.

enhancement: org-wide github runners for cloud deploys

---

aws-github/terraform/aws/eks/main.tf
aws-gitlab/terraform/aws/eks/main.tf

Without this fix, running `aws destroy` more than once if there is a failure can end like this:
```bash
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: ╷
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: │ Error: Invalid function argument
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: │
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: │   on eks/main.tf line 7, in provider "kubernetes":
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: │    7:   cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
2023-03-20T15:41 WRN kubefirst/pkg/ExecShellWithVars/shell.go:97 > ERR: │     ├────────────────
2023-03-20T15:41 WRN …
```

fix: fix terraform failure on re-apply during destroy if obj is null

---

aws-github/cluster-types/mgmt/components/production/metaphor/values.yaml
aws-github/cluster-types/mgmt/components/staging/metaphor/values.yaml
aws-gitlab/cluster-types/mgmt/components/production/metaphor/values.yaml
aws-gitlab/cluster-types/mgmt/components/staging/metaphor.yaml
aws-gitlab/cluster-types/mgmt/components/staging/metaphor/values.yaml
civo-github/cluster-types/mgmt/components/production/metaphor/values.yaml
civo-github/cluster-types/mgmt/components/staging/metaphor/values.yaml
civo-gitlab/cluster-types/mgmt/components/production/metaphor/values.yaml
civo-gitlab/cluster-types/mgmt/components/staging/metaphor/values.yaml
digitalocean-github/cluster-types/mgmt/components/production/metaphor/values.yaml
digitalocean-github/cluster-types/mgmt/components/staging/metaphor/values.yaml
digitalocean-gitlab/cluster-types/mgmt/components/production/metaphor/values.yaml
digitalocean-gitlab/cluster-types/mgmt/components/staging/metaphor/values.yaml
gcp-github/cluster-types/mgmt/components/production/metaphor/values.yaml
gcp-github/cluster-types/mgmt/components/staging/metaphor/values.yaml
gcp-gitlab/cluster-types/mgmt/components/production/metaphor/values.yaml
gcp-gitlab/cluster-types/mgmt/components/staging/metaphor/values.yaml
vultr-github/cluster-types/mgmt/components/production/metaphor/values.yaml
vultr-github/cluster-types/mgmt/components/staging/metaphor/values.yaml
vultr-gitlab/cluster-types/mgmt/components/production/metaphor/values.yaml
vultr-gitlab/cluster-types/mgmt/components/staging/metaphor/values.yaml

@sudowing reported vault secrets in metaphor staging/production aren't updating. turns out all non-k3d platforms are leveraging chart-default development/metaphor path. this fix addresses across all clouds.

fix: staging/production metaphor secrets paths

---

gcp-github/terraform/gcp/kms.tf
gcp-github/terraform/gcp/storage.tf
gcp-github/terraform/gcp/variables.tf
gcp-gitlab/terraform/gcp/kms.tf
gcp-gitlab/terraform/gcp/storage.tf
gcp-gitlab/terraform/gcp/variables.tf

if you can't force destroy the bucket then the destroy function fails and things don't clean up.
Somethings in gcp don't delete right away and the names cannot be reused. The random string (which shouldn't change) will allow us to reuse the cluster name without conflicting resources that either don't clean up right away or have restrictions on name reuse.

feat- add option to destroy buckets

---

gcp-github/cluster-types/mgmt/components/vault/application.yaml
gcp-github/terraform/gcp/kms.tf
gcp-github/terraform/gcp/storage.tf
gcp-github/terraform/gcp/terraform.tfvars
gcp-github/terraform/gcp/variables.tf
gcp-gitlab/cluster-types/mgmt/components/vault/application.yaml
gcp-gitlab/terraform/gcp/kms.tf
gcp-gitlab/terraform/gcp/storage.tf
gcp-gitlab/terraform/gcp/terraform.tfvars
gcp-gitlab/terraform/gcp/variables.tf

had a feeling using terraform for the random string would bite me. I need to use it in detokenization so vault can unseal (needs the keyring name which I made unique) so I'll have to generate the uniqueness in code

fix: add uniqueness from code instead of terraform

---

gcp-github/terraform/gcp/gke/main.tf
gcp-github/terraform/gcp/gke/nat.tf
gcp-github/terraform/gcp/vpc.tf
gcp-gitlab/terraform/gcp/gke/main.tf
gcp-gitlab/terraform/gcp/gke/nat.tf
gcp-gitlab/terraform/gcp/vpc.tf

**Of note, this is tested 1x and with google dns**.
You can enable gke private nodes, while retaining a public endpoint
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/2f5a2769fada01333b178d0bc9ec1e8192535043/modules/private-cluster
```HCL
module "gke" {
source                     = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
enable_private_endpoint    = false
enable_private_nodes       = true
```
This might be a workable and, at least slightly, more secure default near https://github.com/kubefirst/gitops-template/blob/ef737f88cf87216f05d8459da69d7d2d0f673b45/gcp-github/terraform/gcp/gke/main.tf#L12

feat: default to private nodes on gcp gke

---

google-github/terraform/google/gke/nat.tf

Updates nat.tf to 5.0, which was the cause of a hang up in the Terraform installation process for GCP/Google Install Configurations. 
Fix was suggested in kubefirst slack by `@DrummyFloyd`: [here](https://kubefirst.slack.com/archives/C03U34WJ7FW/p1699133610938569?thread_ts=1699123349.084229&cid=C03U34WJ7FW)

Fix: Solves broken GCP Github Terraform Install Process 

---

aws-github/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
aws-gitlab/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
civo-github/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
civo-gitlab/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
digitalocean-github/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
digitalocean-gitlab/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
google-github/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
google-gitlab/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
k3d-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
k3d-gitlab/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
vultr-github/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml
vultr-gitlab/templates/mgmt/components/argo-workflows/cwfts/cwft-helm.yaml

If the shortSha contains an 'e' on the third to the last character, it was misinterpreted by the sed command hence writing an invalid version in the helm chart chart.yaml
For example a shortSha variable, holding a value of "6063e25", was misinterpreted as a numerical value in scientific notation by the system, generating an appVersion of "6.063e+28" instead of appVersion: "6063e25".
The fix is ensuring that shortSha is always treated as a string.

Preventing the miss-interpretation of the appVersion

---

k3d-github/cluster-types/mgmt/crossplane.yaml
k3d-gitlab/cluster-types/mgmt/crossplane.yaml

Love seeing Crossplane in k3d by default! Unfortunately since we don't yet have cluster management in local the subdirectory of `clusters` breaks things.
The error I saw in Argo was:
```
rpc error: code = Unknown desc = registry/clusters/kubefirst/components/crossplane: app path does not exist
```
Screenshots:

Fix: remove `clusters` subdirectory for crossplane

---

.github/workflows/terraform.yml
akamai-github/terraform/akamai/main.tf
akamai-github/terraform/users/modules/user/github/main.tf
akamai-github/terraform/vault/kubernetes-auth-backend.tf
akamai-github/terraform/vault/main.tf
akamai-github/terraform/vault/variables.tf

in #712 I added `make fmt` in the terraform GHA CI, which will only run `terraform fmt` but not check for proper formatting - sorry for that. This CI fixes this and formats all *.tf files correctly.

fix(tffmt): fix CI and run terraform fmt

---

.github/workflows/terraform.yml

Preventing the GitHub warnings with actions using outdated Node.js versions.

update actions/checkout & hashicorp/setup-terraform to latest versions

---

google-github/terraform/google/gke/main.tf
google-gitlab/terraform/google/gke/main.tf

The [deprovision instructions](https://docs.kubefirst.io/gcp/deprovision) don't work without `deletion_protection` set to false.
Defaulting to protecting clusters from being deleted [was added in v5](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster) of the Terraform dependency.
The only question is whether this should be a configurable flag?

remove delete protection from gke

---

google-github/templates/mgmt/components/argocd/argocd-cmd-params-cm.yaml
google-github/templates/mgmt/components/argocd/kustomization.yaml
google-gitlab/templates/mgmt/components/argocd/argocd-cmd-params-cm.yaml
google-gitlab/templates/mgmt/components/argocd/kustomization.yaml

Add files from #597 to Google to avoid argocd.kubefirst.<domain> from infinitely redirecting to itself

add config map to avoid argo from infinitely redirecting

---

google-github/templates/workload-cluster/0-providerconfig.yaml
google-github/templates/workload-cluster/10-infrastructure.yaml
google-github/templates/workload-cluster/20-argocd-connection.yaml
google-github/templates/workload-cluster/30-cert-manager.yaml
google-github/templates/workload-cluster/30-external-dns.yaml
google-github/templates/workload-cluster/30-external-secrets-operator.yaml
google-github/templates/workload-cluster/30-ingress-nginx.yaml
google-github/templates/workload-cluster/30-reloader.yaml
google-github/templates/workload-cluster/40-clusterissuers.yaml
google-github/templates/workload-cluster/40-clustersecretstore.yaml
google-github/templates/workload-cluster/45-environment.yaml
google-github/templates/workload-cluster/appproject-workload-cluster.yaml
google-github/templates/workload-cluster/cert-issuers/clusterissuers.yaml
google-github/templates/workload-cluster/cluster-secret-store/clustersecretstore.yaml
google-github/templates/workload-cluster/infrastructure/wait.yaml
google-github/templates/workload-cluster/infrastructure/workspace.yaml
google-github/templates/workload-cluster/provider-config/providerconfig.yaml
google-github/templates/workload-cluster/registry-workload-cluster.yaml

This adds the option to create a physical GKE cluster in Kubefirst
Before this is merged, I have a couple of questions about how this should be done best.
* The console has "cloud zone" as a required field, but I've done this across all zones which arguably better for prod-grade clusters. Should we change the console to cater for per-zone and multi-zone?
* The console assumes a static number of nodes - should we allow autoscaling with min/max nodes and static number of nodes?
Fixes #765
> I have a dev version running. I can sync with reviewer(s) to use this
1. Create a dev deployment of Kubefirst to Google
2. Create a physical cluster in the dashboard
3. Profit
NB. Physical clusters in GCP are a paid-feature. There is a [Posthog feature …

Add physical cluster templates to Google Cloud Project

---

aws-gitlab/terraform/vault/secrets.tf

The root cause was actually that the URL was set to `registry.gitlab.io` rather than `registry.gitlab.com`
Fixes https://github.com/kubefirst/kubefirst/issues/2256
Deploy to AWS GitLab, using instructions from #783

fix(aws-gitlab): update gitlab url for image registry secret

---

akamai-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
akamai-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
aws-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
aws-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
aws-gitlab/templates/mgmt/components/argo-workflows/vault-wait.yaml
aws-gitlab/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
civo-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
civo-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
civo-gitlab/templates/mgmt/components/argo-workflows/vault-wait.yaml
civo-gitlab/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
digitalocean-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
digitalocean-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
digitalocean-gitlab/templates/mgmt/components/argo-workflows/vault-wait.yaml
digitalocean-gitlab/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
google-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
google-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
google-gitlab/templates/mgmt/components/argo-workflows/vault-wait.yaml
google-gitlab/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
vultr-github/templates/mgmt/components/argo-workflows/vault-wait.yaml
vultr-github/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml
vultr-gitlab/templates/mgmt/components/argo-workflows/vault-wait.yaml
vultr-gitlab/templates/mgmt/components/argo-workflows/wait/vault-tls.yaml

A Job resource is an immutable resource. Changes to spec.template causes a sync error. Add annotation to force replaces Job resources.
Remove  the sync option "replace" from vault-wait ArgoCD app and add to the Job resource as SA and CRB resources do not need to be replaced.
https://github.com/kubefirst/kubefirst/issues/2264
Provision a management cluster and verify `vault-wait` job is healthy.

fix: force replace Job during a sync

---

aws-github/templates/mgmt/components/argocd/kustomization.yaml
aws-github/terraform/aws/eks/main.tf
aws-github/terraform/aws/modules/workload-cluster/main.tf
aws-gitlab/templates/mgmt/components/argocd/kustomization.yaml
aws-gitlab/terraform/aws/eks/main.tf
aws-gitlab/terraform/aws/modules/workload-cluster/main.tf

upgraded eks version to 20.10.0(replaced aws auth module with access entries, as per documentation it wont be supported in v21.x.x) ,k8s verison to 1.29 as support for 1.26 ending 2025,also referenced argo to version 2.12 (new manifest created on Konstruct)

feat: upgrade the AWS EKS cluster, the Kubernetes version it runs, and the version of Argo 

---

akamai-github/templates/mgmt/components/argocd/kustomization.yaml
akamai-github/terraform/akamai/main.tf

point argo verison to 2.12
build the kubefirst binary locally and have kubefirst-api running locally,and run "./kubefirst beta akamai --alerts-email <ALERTS_EMAIL> --github-org <GITHUB_ORG> --gitops-template-branch akamai-upgrade --domain-name <DOMAIN_NAME> --cluster-name <CLUSTER_NAME>"

Akamai upgrade

---

akamai-github/templates/mgmt/components/kubefirst/console.yaml
aws-github/templates/mgmt/components/kubefirst/console.yaml
aws-gitlab/templates/mgmt/components/kubefirst/console.yaml
civo-github/templates/mgmt/components/kubefirst/console.yaml
civo-gitlab/templates/mgmt/components/kubefirst/console.yaml
digitalocean-github/templates/mgmt/components/kubefirst/console.yaml
digitalocean-gitlab/templates/mgmt/components/kubefirst/console.yaml
google-github/templates/mgmt/components/kubefirst/console.yaml
google-gitlab/templates/mgmt/components/kubefirst/console.yaml
k3d-github/cluster-types/mgmt/components/argocd/kustomization.yaml
k3d-github/cluster-types/mgmt/components/kubefirst/console-arm.yaml
k3d-github/cluster-types/mgmt/components/kubefirst/console.yaml
k3d-gitlab/cluster-types/mgmt/components/argocd/kustomization.yaml
k3d-gitlab/cluster-types/mgmt/components/kubefirst/console-arm.yaml
k3d-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
k3s-github/templates/mgmt/components/argocd/kustomization.yaml
k3s-github/templates/mgmt/components/kubefirst/console.yaml
k3s-gitlab/templates/mgmt/components/argocd/kustomization.yaml
k3s-gitlab/templates/mgmt/components/kubefirst/console.yaml
vultr-github/templates/mgmt/components/kubefirst/console.yaml
vultr-gitlab/templates/mgmt/components/kubefirst/console.yaml

changed kubefirst charts reference to Konstruct
use the kubefirst binary and add the flag "--gitops-template-branch k3d-upgrade"

feat,fix: Konstruct chart reference and K3d upgrade

---

akamai-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
akamai-github/templates/mgmt/components/vault/application.yaml
aws-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
aws-github/templates/mgmt/components/vault/application.yaml
aws-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
aws-gitlab/templates/mgmt/components/vault/application.yaml
civo-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
civo-github/templates/mgmt/components/vault/application.yaml
civo-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
civo-gitlab/templates/mgmt/components/vault/application.yaml
digitalocean-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
digitalocean-github/templates/mgmt/components/vault/application.yaml
digitalocean-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
digitalocean-gitlab/templates/mgmt/components/vault/application.yaml
google-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
google-github/templates/mgmt/components/vault/application.yaml
google-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
google-gitlab/templates/mgmt/components/vault/application.yaml
k3d-github/cluster-types/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
k3d-github/cluster-types/mgmt/components/vault/application.yaml
k3d-gitlab/cluster-types/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
k3d-gitlab/cluster-types/mgmt/components/vault/application.yaml
k3s-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
k3s-github/templates/mgmt/components/vault/application.yaml
k3s-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
k3s-gitlab/templates/mgmt/components/vault/application.yaml
vultr-github/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
vultr-github/templates/mgmt/components/vault/application.yaml
vultr-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-system.yaml
vultr-gitlab/templates/mgmt/components/vault/application.yaml

bump crossplane to 1.17.0 and vault to 0.28.1
when provisioning a cluster,use "--gitops-template-branch vault-crossplane-upgrade" flag

feat:upgrade vault and crossplane version

---

aws-github/templates/mgmt/components/argocd/argocd-cm.yaml
aws-github/templates/workload-cluster/provider-config/providerconfig.yaml
aws-github/terraform/aws/modules/workload-cluster/main.tf
aws-gitlab/templates/mgmt/components/argocd/argocd-cm.yaml
aws-gitlab/templates/workload-cluster/provider-config/providerconfig.yaml
aws-gitlab/terraform/aws/modules/workload-cluster/main.tf

PR adds
- Add an access entry for argocd in workload account. 
- Add custom health check for `tf.upbound.io/Workspace`
- Use `assume_role_with_web_identity` feature
Run the cluster.

fix(EKS): multi-account ArgoCD access  

---

akamai-github/templates/mgmt/components/argocd/kustomization.yaml
aws-github/templates/mgmt/components/argocd/argocd-cm.yaml
aws-github/templates/mgmt/components/argocd/kustomization.yaml
aws-github/terraform/aws/modules/workload-cluster/main.tf
aws-gitlab/templates/mgmt/components/argocd/argocd-cm.yaml
aws-gitlab/templates/mgmt/components/argocd/kustomization.yaml
aws-gitlab/terraform/aws/modules/workload-cluster/main.tf
civo-github/templates/mgmt/components/argocd/kustomization.yaml
civo-gitlab/templates/mgmt/components/argocd/kustomization.yaml
digitalocean-github/templates/mgmt/components/argocd/kustomization.yaml
digitalocean-gitlab/templates/mgmt/components/argocd/kustomization.yaml
google-github/templates/mgmt/components/argocd/kustomization.yaml
google-gitlab/templates/mgmt/components/argocd/kustomization.yaml
k3s-github/templates/mgmt/components/argocd/kustomization.yaml
k3s-gitlab/templates/mgmt/components/argocd/kustomization.yaml
vultr-github/templates/mgmt/components/argocd/kustomization.yaml
vultr-gitlab/templates/mgmt/components/argocd/kustomization.yaml

This PR
- Fix: change suffix for principalARN from `cluster name` to management's cluster name
- Update argo-cd manifest to v1.1.1 which includes resource health check for Crossplane Workspace resource.

fix: aws multi

---

aws-github/templates/mgmt/components/argocd/argocd-oidc-restart-job.yaml
aws-gitlab/templates/mgmt/components/argocd/argocd-oidc-restart-job.yaml

For various reasons Argo CD is a two part installation; where it is intially installed from [here](https://github.com/konstructio/gitops-template/blob/main/aws-github/templates/mgmt/components/argocd/argocd-oidc-restart-job.yaml) and then once it is up it takes controller of managing and patching itself. Seconds steps involves performing cloud specific operation such as annotation the service account with IAM role arn. Since there is no straight forward mechanics to trigger a rollout when using Kustomize, unlike Helm where you can add an annotation with the SHA of the service account or resource you are dependent on. This PR updates an existing job to gracefully restart ArgoCD server and application controller. 
(AWS) ArgoCD fails to communicate with downstream clusters.
Create a test …

feat(aws): gracefully restart argocd server and application controller

---

civo-github/templates/gpu-cluster/provider-config/providerconfig.yaml
civo-github/templates/workload-cluster/provider-config/providerconfig.yaml
civo-github/terraform/civo/main.tf
civo-gitlab/templates/gpu-cluster/provider-config/providerconfig.yaml
civo-gitlab/templates/workload-cluster/provider-config/providerconfig.yaml
civo-gitlab/terraform/civo/main.tf

download the 1.1.0 version rather than the latest version ,as the latest version has breaking changes for naming convention

fix: download the stable 1.1.0 Civo tf provider

---

azure-github/templates/workload-vcluster/30-ingress-nginx.yaml

For vclusters, this correctly routes traffic (previously wasn't working at all as had forgotten to check it).
Fixes #
1. Deploy an Azure cluster and check the load balancer's healthcheck.
2. Create a vcluster and deploy flappy-kray
Or, use my existing cluster - https://flappy-kray.azure-kubefirst4.simonemms.com/

fix(azure-github): update the ingress-nginx config

---

civo-github/templates/gpu-cluster/provider-config/providerconfig.yaml
civo-github/templates/mgmt/cloud-accounts.yaml
civo-github/templates/mgmt/components/cloud-accounts/default-civo-account.yaml
civo-github/templates/workload-cluster/provider-config/providerconfig.yaml
civo-github/terraform/vault/secrets.tf
civo-gitlab/templates/gpu-cluster/provider-config/providerconfig.yaml
civo-gitlab/templates/workload-cluster/provider-config/providerconfig.yaml
civo-gitlab/terraform/vault/secrets.tf

1.Remove Civo Token from Vault Secrets:
The Civo API token has been removed from the secrets stored in Vault. The Crossplane Terraform provider will no longer utilize this token
2.Reference JSON Secret During Provisioning:
A JSON secret, created at the time of provisioning, will be referenced in the Crossplane system from Vault. This secret will be utilized during the provisioning process and subsequently deleted from the Crossplane namespace once the cluster has been provisioned.
pass the flag of "--gitops-template-branch civo-multi-account" when proivisoning a cluster and test the multiaccount provisioning by inserting appropriate keys for downstream accounts

feat: add json file in terraform for Civo Multi account

---

azure-github/templates/mgmt/components/argo-workflows/application.yaml
azure-github/templates/mgmt/components/argo-workflows/externalsecret.yaml
azure-gitlab/templates/mgmt/components/argo-workflows/application.yaml
azure-gitlab/templates/mgmt/components/argo-workflows/externalsecret.yaml

Updates the Argo workflow configuration is done so that the artifacts are stored correctly. The storage container uses credentials from the ChartMuseum Vault secret.
- [Working GitHub Action](https://github.com/mrsimonemmsorg2/metaphor/actions/runs/12031531209)
- [Working GitLab Action](https://gitlab.com/sje-kubefirst/metaphor/-/pipelines/1561052814)
This now publishes the Metaphor app to the cluster:
- [GitHub example](https://metaphor-development.azure2.kubefirst.simonemms.com/)
- [GitLab example](https://metaphor-development.azure3.kubefirst.simonemms.com/)
I've added [Reload](https://docs.stakater.com/reloader/) annotations to the server and controller for the configmap and secrets used to reload the pods if the configmap and secret changes - if there's an already workflow, this …

fix(azure): update argo workflows to store artifacts correctly

---

azure-gitlab/templates/workload-cluster/0-providerconfig.yaml
azure-gitlab/templates/workload-cluster/10-infrastructure.yaml
azure-gitlab/templates/workload-cluster/20-argocd-connection.yaml
azure-gitlab/templates/workload-cluster/30-cert-manager.yaml
azure-gitlab/templates/workload-cluster/30-external-dns.yaml
azure-gitlab/templates/workload-cluster/30-external-secrets-operator.yaml
azure-gitlab/templates/workload-cluster/30-ingress-nginx.yaml
azure-gitlab/templates/workload-cluster/30-reloader.yaml
azure-gitlab/templates/workload-cluster/40-cloudflare-origin-issuer-crd.yaml
azure-gitlab/templates/workload-cluster/40-clusterissuers.yaml
azure-gitlab/templates/workload-cluster/40-clustersecretstore.yaml
azure-gitlab/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
azure-gitlab/templates/workload-cluster/45-cloudflare-origin-issuer.yaml
azure-gitlab/templates/workload-cluster/45-environment.yaml
azure-gitlab/templates/workload-cluster/appproject-workload-cluster.yaml
azure-gitlab/templates/workload-cluster/bootstrap/wait.yaml
azure-gitlab/templates/workload-cluster/cert-issuers/clusterissuers.yaml
azure-gitlab/templates/workload-cluster/cluster-secret-store/clustersecretstore.yaml
azure-gitlab/templates/workload-cluster/infrastructure/wait.yaml
azure-gitlab/templates/workload-cluster/infrastructure/workspace.yaml
azure-gitlab/templates/workload-cluster/provider-config/providerconfig.yaml
azure-gitlab/templates/workload-cluster/registry-workload-cluster.yaml
azure-gitlab/terraform/azure/cluster.tf
azure-gitlab/terraform/azure/main.tf
azure-gitlab/terraform/azure/modules/workload-cluster/cluster.tf
azure-gitlab/terraform/azure/modules/workload-cluster/main.tf
azure-gitlab/terraform/azure/modules/workload-cluster/network.tf
azure-gitlab/terraform/azure/modules/workload-cluster/secrets.tf
azure-gitlab/terraform/azure/modules/workload-cluster/variables.tf
azure-gitlab/terraform/vault/secrets.tf

Create physical clusters for Azure GitLab
Fixes #
Build an Azure cluster pointing to this branch in the GitOps templates. Until the console work is done, this will require manually adding the `gitops` repo:
1. Copy `templates/workload-cluster` to `registry/<cluster-name>`
2. Move `registry/<cluster-name>/appproject-workload-cluster.yaml` to `registry/clusters/<mgmt>/components/argocd-appprojects`
3. Move `registry/<cluster-name>/registry-workload-cluster.yaml` to `registry/clusters/<mgmt>`
4. Search and replace the following values:
- `<WORKLOAD_CLUSTER_NAME>`: `<cluster-name>`
- `<WORKLOAD_CLUSTER_REGION>`: `ukwest`
- `<WORKLOAD_NODE_COUNT>`: `3`
- `<WORKLOAD_NODE_TYPE>`: `Standard_D2s_v4`
- `<WORKLOAD_EXTERNAL_DNS_DOMAIN_NAME>`: `<domain name>` (see …

Build real clusters in Azure GitLab

---

aws-github/terraform/aws/eks/main.tf
aws-gitlab/terraform/aws/eks/main.tf

change service account name to establish a valid trust relationship between Kubefirst and AWS ([Link to change](https://github.com/konstructio/kubefirst-pro-api/commit/f68ea061ac665d9e48200703be9043d6b9e5ea69))

fix: service account name

---

vultr-github/terraform/vultr/main.tf
vultr-gitlab/terraform/vultr/main.tf

This uses the current patch version of K8s on Vultr per 
https://github.com/konstructio/kubefirst/issues/2261
Fixes #2261 (issue in main kubefirst repo)
Create a cluster on Vultr without this change, it will fail with an error `Invalid k8 version`. With this change, the `terraform apply` step will be successful and the `kubefirst beta vultr create ...` command is successful!

fix: Use current patch version of 1.30 on Vultr

---

aws-gitlab/terraform/vault/secrets.tf
civo-gitlab/terraform/vault/secrets.tf
digitalocean-gitlab/terraform/vault/secrets.tf
google-gitlab/terraform/vault/secrets.tf
k3d-gitlab/terraform/vault/secrets.tf
k3s-gitlab/terraform/vault/secrets.tf
vultr-gitlab/terraform/vault/secrets.tf

I caught a small typo in the `/deploy-tokens/container-registry-auth` vault secret for all gitlab deployments. I discovered this while troubleshooting some authentication issues (although, this typo turned out to be unrelated to that). Thanks for all your work!
N/A
N/A

fix: correct typo in vault/secrets.tf for gitlab deployments

---

renovate.json

based on this comment from slack 
https://kubefirst.slack.com/archives/C03U34WJ7FW/p1703867034753859
i though to have have such automated mechanism, would be a game changer for the ops template 
that's why i came with a quick implementaiton of `renovate` 
this bot will create PR for all argocd APP:kustomization and terraform .
i make a the default setting for the AUTOMERGE( but can be easily change in the JSON file , we can discuss about it if you want) (all config options are [here](https://docs.renovatebot.com/configuration-options/)
for me you can allow ALL to an AUTOmerge (in FF mode ) (fastforward merge lover here) .
because you provide a template on a one time based . so no risk to break anything on update in customer side. ( but maybe i'm wrong about it)
meanwhile, 
you have to …

feat: add auto bump version ops template

---

aws-github/terraform/aws/eks/main.tf
aws-github/terraform/aws/modules/workload-cluster/main.tf
aws-gitlab/terraform/aws/eks/main.tf
aws-gitlab/terraform/aws/modules/workload-cluster/main.tf

PR updates k8s versin to `v1.31`. 
- Starting v1.30, EKS no longer comes with a default storage class. [docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.30)
To create a new cluster run API and console locally. Use `KRA-49` branch for gitops-template.

KRA-49 feat: update EKS to 1.31 

---

vultr-github/terraform/vultr/main.tf
vultr-github/terraform/vultr/modules/workload-cluster/main.tf
vultr-gitlab/terraform/vultr/main.tf

Update management and workload cluster Kubernetes version to `v1.31.5+1`.
Fixes #
- Vultr dropped support for `v1.30.6+1`
Create Kubefirst platform in Vultr using this branch.

feat: update Kubernetes version to v1.31.5+1

---

aws-gitlab/templates/workload-cluster/infrastructure-bootstrap/wait.yaml
aws-gitlab/templates/workload-cluster/infrastructure/wait.yaml
aws-gitlab/templates/workload-cluster/infrastructure/workspace.yaml

Add support for ami type in downstream clusters 
provision the mgmt aws cluster using flag '--gitops-template-branch ami-gitlab` and provision physical clusters

feat: add ami support for gitlab

---

aws-github/terraform/aws/modules/workload-cluster/main.tf

- Disables ipv6 for aws workload clusters

fix: aws disable ipv6 for workload clusters
