- terraform/users/admin.tf
- terraform/users/developers.tf
- terraform/users/kubefirst.tf
admins: kubefirst repo owners
developer: kubefirst repo developers
closes #81
> adding gitlab groups as kubefirst group members

- components/argocd/application.yaml
> argocd-exclusive-secret

- components/argocd/application.yaml
> fix-secret-name-according-docs

- components/development/metaphor-frontend.yaml
- components/development/metaphor-frontend/Chart.yaml
- components/development/metaphor-frontend/values.yaml
- components/production/metaphor-frontend.yaml
- components/production/metaphor-frontend/Chart.yaml
- components/production/metaphor-frontend/values.yaml
- components/staging/metaphor-frontend.yaml
- components/staging/metaphor-frontend/Chart.yaml
- components/staging/metaphor-frontend/values.yaml
> feat: add metaphor frontend

- terraform/base/eks/main.tf
- terraform/base/eks/variables.tf
- terraform/base/main.tf
- terraform/base/variables.tf
Task completed during the engineering day, which allows runs spot nodes on eks node groups.
This PR depends: https://github.com/kubefirst/kubefirst/pull/200
> nodes_spot

- terraform/base/eks/main.tf
updated terraform modules to the first version with apple arm64 support
> update version to support apple arm64

- components/argo/cwfts/cwft-docker.yaml
- components/development/metaphor-frontend.yaml
- components/development/metaphor-frontend/Chart.yaml
- components/development/metaphor-frontend/values.yaml
- components/development/metaphor-go.yaml
- components/development/metaphor-go/Chart.yaml
- components/development/metaphor-go/values.yaml
- components/production/metaphor-frontend.yaml
- components/production/metaphor-frontend/Chart.yaml
- components/production/metaphor-frontend/values.yaml
- components/production/metaphor-go.yaml
- components/production/metaphor-go/Chart.yaml
- components/production/metaphor-go/values.yaml
- components/staging/metaphor-frontend.yaml
- components/staging/metaphor-frontend/Chart.yaml
- components/staging/metaphor-frontend/values.yaml
- components/staging/metaphor-go.yaml
- components/staging/metaphor-go/Chart.yaml
- components/staging/metaphor-go/values.yaml
- terraform/gitlab/kubefirst-repos.tf
> feat: add metaphor-go components

- components/argo/cwfts/cwft-docker.yaml
- components/development/metaphor-frontend.yaml
- components/development/metaphor-frontend/Chart.yaml
- components/development/metaphor-frontend/values.yaml
- components/development/metaphor-go.yaml
- components/development/metaphor-go/Chart.yaml
- components/development/metaphor-go/values.yaml
- components/production/metaphor-frontend.yaml
- components/production/metaphor-frontend/Chart.yaml
- components/production/metaphor-frontend/values.yaml
- components/production/metaphor-go.yaml
- components/production/metaphor-go/Chart.yaml
- components/production/metaphor-go/values.yaml
- components/staging/metaphor-frontend.yaml
- components/staging/metaphor-frontend/Chart.yaml
- components/staging/metaphor-frontend/values.yaml
- components/staging/metaphor-go.yaml
- components/staging/metaphor-go/Chart.yaml
- components/staging/metaphor-go/values.yaml
- terraform/gitlab/kubefirst-repos.tf
Synch  with main to add metaphors
> V19x plus metaphor

- terraform/vault/bootstrap/secrets.tf
- terraform/vault/bootstrap/variables.tf
- terraform/vault/variables.tf
closes: https://github.com/kubefirst/kubefirst/issues/337
> add ssh_private_key var to be used in git

- terraform/vault/main.tf
Fixes:
- [#337](https://github.com/kubefirst/kubefirst/issues/337)
> Issue 337 - Fix

- components/argo-gitlab/cwfts.yaml
- components/development/metaphor-frontend.yaml
- components/development/metaphor-go.yaml
- components/production/metaphor-frontend.yaml
- components/production/metaphor-go.yaml
- components/staging/metaphor-frontend.yaml
- components/staging/metaphor-go.yaml
Fix repo address, to follow new tokens
> Fix templates 20220909

- terraform/ecr/main.tf
TFs to create ECR on AWS to Github flavor.
We should improve this in a near future, creating the ECRs dynamically.
> tf to ecr (metaphor apps)

- terraform/ecr/main.tf
> fix_aws_region

- terraform/users/modules/user/github/main.tf
the docs i read so you can check my math
https://www.terraform.io/language/expressions/conditionals#syntax
> leverage var.initial_password when provided

- terraform/users/admins-gitlab.tf
- terraform/users/developers-gitlab.tf
- https://github.com/kubefirst/kubefirst/issues/514
> 514 - rename admin gitlab

- components/gitlab/argocd-adopts-gitlab.yaml
> Fix error post adopt to gitlab

- components/github-runner/github-runner.yaml
Signed-off-by: Jessica Marinho <jessica@kubeshop.io>
> Fix string to be detokenized with github-owner value

- localhost/terraform/vault/secrets-github.tf
Signed-off-by: Jessica Marinho <jessica@kubeshop.io>
> Change vault port

- localhost/components/atlantis/application.yaml
- localhost/terraform/github/remote-backend.md
- localhost/terraform/users/kubefirst-github.tf
- localhost/terraform/vault/main.tf
> chore: add minio localdev

- components/argo-github/ingress.yaml
- components/argo-gitlab/ingress.yaml
- components/argocd-github/application.yaml
- components/argocd-gitlab/application.yaml
- components/atlantis/application.yaml
- components/chartmuseum/ingress.yaml
- components/development/metaphor-frontend/values.yaml
- components/development/metaphor-go/values.yaml
- components/development/metaphor/values.yaml
- components/kubefirst/console.yaml
- components/kubefirst/vouch.yaml
- components/production/metaphor-frontend/values.yaml
- components/production/metaphor-go/values.yaml
- components/production/metaphor/values.yaml
- components/staging/metaphor-frontend/values.yaml
- components/staging/metaphor-go/values.yaml
- components/staging/metaphor/values.yaml
- components/vault/vault.yaml
- registry/gitlab.yaml
Reverts kubefirst/gitops-template#201
Needs to include dns resolver and want to work through that with the team.
> Revert "wildcard certs"

- terraform/users/developers-gitlab.tf
- terraform/users/modules/user/github/main.tf
- terraform/users/modules/user/gitlab/main.tf
- terraform/vault/policies.tf
Attempt to address:
-  [X] https://github.com/kubefirst/kubefirst/issues/748
> Update policies.tf - add devs powers to update their password on vault

- localhost/registry/development.yaml
- localhost/registry/production.yaml
- localhost/registry/staging.yaml
Related to: 
- https://github.com/kubefirst/kubefirst/pull/819
Solves: 
- https://github.com/kubefirst/kubefirst/issues/813
Make metaphor selectable by addon.
> Make metaphor an addon

- components/chartmuseum/application.yaml
- registry/aws-auth.yaml
- terraform/base/eks/main.tf
- terraform/base/kms/main.tf
Reverts kubefirst/gitops-template#224
> Revert "fix eks node role token"

- components/chartmuseum/application.yaml
- registry/aws-auth.yaml
- terraform/base/eks/main.tf
- terraform/base/kms/main.tf
Reverts kubefirst/gitops-template#225
> Revert "Revert "fix eks node role token""

- localhost/components/development/ingressroute.yaml
> chore: update tls secret path

- localhost/terraform/users/kubefirst-gitlab.tf
- localhost/terraform/users/modules/user/gitlab/main.tf
- localhost/terraform/vault/oidc-provider.tf
- terraform/gitlab/modules/repository/versions.tf
- terraform/gitlab/versions.tf
- terraform/users/kubefirst-gitlab.tf
- terraform/users/modules/user/gitlab/main.tf
- terraform/vault/main.tf
Fix(gitlab breaking change): 
-  https://github.com/kubefirst/kubefirst/issues/1013
Notes:
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/guides/version-15.7-upgrade
Thanks @pagottoo 
Signed-off-by: 6za <53096417+6za@users.noreply.github.com>
> fix: kubefirst#1013

- terraform/users/modules/user/gitlab/main.tf
Fix:  
- https://github.com/kubefirst/kubefirst/issues/1047
> fix: 1047 - gitlab kbot inital password not working

- localhost/terraform/vault/oidc-provider.tf
Explicit verification_ttl to verify the correction of intermittence in the installation of the vault in terraform of localhost.
Signed-off-by: Jessica Marinho <jessica@kubeshop.io>
> Add verification ttl

- localhost/terraform/users/admins-github.tf
- terraform/users/admins-github.tf
required for e2e test, it will uncomment the line to create a new user.
> chore: add commented module addition for user

- .github/workflows/terraform.yml
- terraform/vault/secrets-gitlab.tf
Will run `fmt` on each push and fail if Terraform code needs formatting.
> enhancement: add github action for running tf fmt

- README.md
- atlantis.yaml
- civo-github/atlantis.yaml
- civo-github/terraform/github/repos.tf
- civo-github/terraform/users/kubefirst.tf
- localhost/terraform/github/local-backend.tf
- localhost/terraform/github/modules/repository/main.tf
- localhost/terraform/users/kubefirst-github.tf
- terraform/github/modules/repository/main.tf
- terraform/github/repos.tf
- terraform/users/kubefirst-github.tf
- validation/tokens.md
Adds consistency in GitHub Terraform provider versions and bumps Terraform version to latest. Done as a result of bug hunting and ruling out providers.
> Bump GitHub provider versions and Terraform version.

- civo-github/terraform/vault/kubernetes-auth-backend.tf
> Remove duplicate Civo provider

- civo-github/mgmt-cluster-template/components/argo-workflows/cwfts/cwft-buildkit.yaml
Points to the secret created specifically for working with buildkit.
> Fix container registry secret interpolation

- civo-github/cluster-types/mgmt/argocd.yaml
- civo-github/cluster-types/mgmt/components/argocd/argo-cd-cm.yaml
- civo-github/cluster-types/mgmt/components/argocd/argo-cd-namespace.yaml
- civo-github/cluster-types/mgmt/components/argocd/argo-cd-ui-ingress.yaml
- civo-github/cluster-types/mgmt/components/argocd/kustomization.yaml
- civo-gitlab/cluster-types/mgmt/argocd.yaml
- civo-gitlab/cluster-types/mgmt/components/argocd/argo-cd-cm.yaml
- civo-gitlab/cluster-types/mgmt/components/argocd/argo-cd-namespace.yaml
- civo-gitlab/cluster-types/mgmt/components/argocd/argo-cd-ui-ingress.yaml
- civo-gitlab/cluster-types/mgmt/components/argocd/kustomization.yaml
Adds resources for Argo CD declarative management to Civo.
> feat: self-managed argocd for civo

- civo-github/cluster-types/mgmt/components/argocd/argo-cd-ui-ingress.yaml
- civo-gitlab/cluster-types/mgmt/components/argocd/argo-cd-ui-ingress.yaml
The one previously was for k3d.
> bugfix: set ingress config properly for civo

- civo-github/terraform/vault/secrets.tf
- civo-github/terraform/vault/variables.tf
- civo-gitlab/terraform/vault/secrets.tf
- civo-gitlab/terraform/vault/variables.tf
Remove hardcoded default vault token and use parsed secret value from vault init.
> fix: use correct civo vault token

- aws-github/cluster-types/mgmt/components/kubefirst/console.yaml
- aws-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
- civo-github/cluster-types/mgmt/components/kubefirst/console.yaml
- civo-github/terraform/vault/oidc-clients.tf
- civo-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
- civo-gitlab/terraform/vault/oidc-clients.tf
- k3d-github/cluster-types/mgmt/components/kubefirst/console.yaml
- k3d-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
associated with cli changeset
https://github.com/kubefirst/kubefirst/pull/1402/files
> fix: changing token convention to ARGOCD across all stacks

- aws-github/terraform/github/repos.tf
- aws-gitlab/terraform/gitlab/main.tf
fixes https://github.com/kubefirst/kubefirst/issues/1252
> fix: aws tfstate filename

- aws-github/ci/.argo/publish.yaml
- aws-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- aws-gitlab/ci/.argo/publish.yaml
- aws-gitlab/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- civo-github/ci/.argo/publish.yaml
- civo-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- civo-gitlab/ci/.argo/publish.yaml
- civo-gitlab/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- digitalocean-github/ci/.argo/publish.yaml
- digitalocean-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- digitalocean-github/terraform/digitalocean/main.tf
- k3d-github/ci/.argo/publish.yaml
- k3d-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- k3d-gitlab/ci/.argo/publish.yaml
- k3d-gitlab/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- vultr-github/ci/.argo/publish.yaml
- vultr-github/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
- vultr-gitlab/ci/.argo/publish.yaml
- vultr-gitlab/cluster-types/mgmt/components/argo-workflows/cwfts/cwft-kaniko.yaml
https://github.com/GoogleContainerTools/kaniko replaces buildkit for in-cluster image builds
> feat: kaniko replaces buildkit for docker builds

- civo-github/terraform/users/admins/admin-one.tf
- civo-github/terraform/users/developers/developer-one.tf
the commented example for onboarding a user has a bad module directory reference
> fix: user onboard commented example adjustment

- aws-github/terraform/aws/eks/main.tf
- aws-gitlab/terraform/aws/eks/main.tf
Reverts kubefirst/gitops-template#500
> Revert "chore: bump eks version"

- aws-gitlab/cluster-types/mgmt/components/argo-workflows/externalsecret.yaml
- aws-gitlab/terraform/vault/secrets.tf
pulled this from another provider
> fix: correct gitlab container registry auth secret

- aws-github/terraform/users/modules/user/main.tf
- aws-gitlab/terraform/users/modules/user/main.tf
- civo-github/terraform/users/modules/user/github/main.tf
- civo-gitlab/terraform/users/modules/user/main.tf
- digitalocean-github/terraform/users/modules/user/github/main.tf
- digitalocean-gitlab/terraform/users/modules/user/main.tf
- gcp-github/terraform/users/modules/user/github/main.tf
- gcp-gitlab/terraform/users/modules/user/main.tf
- vultr-github/terraform/users/modules/user/github/main.tf
- vultr-gitlab/terraform/users/modules/user/main.tf
> fix: managing user endpoint lifecycle differently for passwords

- akamai-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- akamai-github/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- akamai-github/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- aws-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- aws-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- civo-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- civo-github/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- civo-github/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- civo-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- civo-gitlab/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- civo-gitlab/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- digitalocean-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- digitalocean-github/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- digitalocean-github/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- digitalocean-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- digitalocean-gitlab/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- digitalocean-gitlab/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- google-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- google-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- k3s-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- k3s-gitlab/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- vultr-github/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- vultr-github/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
- vultr-gitlab/templates/mgmt/cloudflare-origin-ca-issuer.yaml
- vultr-gitlab/templates/workload-vcluster/41-cloudflare-origin-ca-issuer.yaml
as discussed on slack :-)
ref: https://github.com/cloudflare/origin-ca-issuer/issues/97#issuecomment-1897139971
> fix: cloudflare origin-ca-issuer chart repo and version

- civo-github/templates/mgmt/components/actions-runner-controller/application.yaml
- civo-github/templates/mgmt/components/github-runner/runnerdeployment.yaml
- metaphor/.github/workflows/main.yaml
this pr introduces the adoption of civo's talos kubernetes option with rootless builds and action runners
> feat: civo github stack adopts talos

- .github/workflows/check-signed.yml
I also upgraded the actions/checkout GitHub Action and made the names clearer.
> Fix the signing commits check GitHub workflow for PRs from forks

- akamai-github/templates/mgmt/components/kubefirst/console.yaml
- k3s-github/templates/mgmt/components/kubefirst/console.yaml
- k3s-gitlab/templates/mgmt/components/kubefirst/console.yaml
bump chart versions for k3s and akamai github
from ci automation
> bump chart versions for k3s and akamai github

- .editorconfig
Fixes https://github.com/kubefirst/kubefirst/issues/2240
> chore: add editorconfig support

- aws-gitlab/templates/mgmt/components/crossplane/crossplane-system/crossplane-secrets.yaml
- aws-gitlab/templates/mgmt/components/kubefirst/console.yaml
- aws-gitlab/templates/workload-cluster/0-providerconfig.yaml
- aws-gitlab/templates/workload-cluster/10-infrastructure.yaml
- aws-gitlab/templates/workload-cluster/15-infrastructure-bootstrap.yaml
- aws-gitlab/templates/workload-cluster/20-argocd-connection.yaml
- aws-gitlab/templates/workload-cluster/30-cert-manager.yaml
- aws-gitlab/templates/workload-cluster/30-external-dns.yaml
- aws-gitlab/templates/workload-cluster/30-external-secrets-operator.yaml
- aws-gitlab/templates/workload-cluster/30-ingress-nginx.yaml
- aws-gitlab/templates/workload-cluster/30-reloader.yaml
- aws-gitlab/templates/workload-cluster/40-clusterissuers.yaml
- aws-gitlab/templates/workload-cluster/40-clustersecretstore.yaml
- aws-gitlab/templates/workload-cluster/45-environment.yaml
- aws-gitlab/templates/workload-cluster/appproject-workload-cluster.yaml
- aws-gitlab/templates/workload-cluster/cert-issuers/clusterissuers.yaml
- aws-gitlab/templates/workload-cluster/cluster-secret-store/clustersecretstore.yaml
- aws-gitlab/templates/workload-cluster/infrastructure-bootstrap/wait.yaml
- aws-gitlab/templates/workload-cluster/infrastructure-bootstrap/workspace.yaml
- aws-gitlab/templates/workload-cluster/infrastructure/wait.yaml
- aws-gitlab/templates/workload-cluster/infrastructure/workspace.yaml
- aws-gitlab/templates/workload-cluster/provider-config/providerconfig.yaml
- aws-gitlab/templates/workload-cluster/registry-workload-cluster.yaml
- aws-gitlab/terraform/aws/eks/main.tf
- aws-gitlab/terraform/aws/modules/bootstrap/bootstrap.tf
- aws-gitlab/terraform/aws/modules/bootstrap/variables.tf
- aws-gitlab/terraform/aws/modules/workload-cluster/main.tf
- aws-gitlab/terraform/aws/modules/workload-cluster/variables.tf
> This is broadly the same as #774, but for GitLab
Fixes #782 
Fixed #764 
See #774 for the test commands as everything is identical from a Console point of view. The required command to create the cluster is:
```bash
../kubefirst/kubefirst aws create \
--alerts-email <email> \
--domain-name <domain> \
--cluster-name <your-cluster-name> \
--gitlab-group <gitlab-group> \
--cloud-region <region> \
--gitops-template-url https://github.com/mrsimonemmsorg/gitops-template.git \
--gitops-template-branch sje/aws-gitlab-cluster \
--git-provider gitlab
```
Note that `gitlab-group`, `gitops-template-branch` and `git-provider` are different to the GitHub command.
> feat(aws-gitlab): add ability to create a physical cluster in aws gitlab

- .devcontainer/devcontainer.json
Provide development environment as code
Fixes #
- Ensure that the [dev container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) extension is installed to VSCode
- Open up repo in VSCode
- When prompted, reopen in container
> chore: add devcontainer support to the project

- akamai-github/templates/mgmt/components/kubefirst/wait.yaml
- aws-github/templates/mgmt/components/kubefirst/wait.yaml
- aws-gitlab/templates/mgmt/components/kubefirst/wait.yaml
- civo-github/templates/mgmt/components/kubefirst/wait.yaml
- civo-gitlab/templates/mgmt/components/kubefirst/wait.yaml
- digitalocean-github/templates/mgmt/components/kubefirst/wait.yaml
- digitalocean-gitlab/templates/mgmt/components/kubefirst/wait.yaml
- google-github/templates/mgmt/components/kubefirst/wait.yaml
- google-gitlab/templates/mgmt/components/kubefirst/wait.yaml
- k3d-github/cluster-types/mgmt/components/kubefirst/wait.yaml
- k3d-gitlab/cluster-types/mgmt/components/kubefirst/wait.yaml
- k3s-github/templates/mgmt/components/kubefirst/wait.yaml
- k3s-gitlab/templates/mgmt/components/kubefirst/wait.yaml
- vultr-github/templates/mgmt/components/kubefirst/wait.yaml
- vultr-gitlab/templates/mgmt/components/kubefirst/wait.yaml
Fixes the kubernetes label to `kubefirst-pro-ui`
> fix: wait label

- vultr-gitlab/terraform/vault/secrets.tf
add correct path for chartmuseum secret in vultr gitlab
> fix: correct chartmuseum secret path

- k3d-github/cluster-types/mgmt/components/kubefirst/console.yaml
- k3d-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
we dont detokensize annotations for k3d,so while syncing it gives error
> fix: remove annotations in ingress for k3d

- metaphor/README.md
Also removed the one that made sense when we only had k3d
> update docs links

- azure-github/templates/workload-vcluster/30-external-dns.yaml
- azure-github/templates/workload-vcluster/bootstrap/workspace.yaml
- azure-github/templates/workload-vcluster/provider-config/providerconfig.yaml
- azure-github/terraform/vault/main.tf
- azure-github/terraform/vault/secrets.tf
Configures vcluster fun for GitHub
Fixes #
> Azure GitHub vcluster setup

- k3d-github/cluster-types/mgmt/components/minio/application.yaml
- k3d-gitlab/cluster-types/mgmt/components/minio/application.yaml
upgrade minio version for k3d GitHub and gitlab
> feat: upgrade minio version

- google-github/templates/workload-cluster/0-providerconfig.yaml
- google-github/templates/workload-cluster/10-infrastructure.yaml
- google-github/templates/workload-cluster/40-clusterissuers.yaml
- google-github/templates/workload-cluster/40-clustersecretstore.yaml
- google-github/templates/workload-cluster/45-environment.yaml
- google-github/templates/workload-cluster/appproject-workload-cluster.yaml
- google-github/templates/workload-cluster/registry-workload-cluster.yaml
> fix remove hard coded repo url

- azure-github/terraform/azure/cluster.tf
- azure-github/terraform/azure/main.tf
- azure-gitlab/terraform/azure/cluster.tf
- azure-gitlab/terraform/azure/main.tf
Update the templates so that the Azure's DNS resource group is optional
Fixes https://github.com/konstructio/kubefirst/issues/2340
See https://github.com/konstructio/kubefirst/pull/2339
> fix(azure): make dns resource group optional

- azure-github/templates/workload-cluster/0-providerconfig.yaml
- azure-github/templates/workload-cluster/10-infrastructure.yaml
- azure-github/templates/workload-cluster/20-argocd-connection.yaml
- azure-github/templates/workload-cluster/30-cert-manager.yaml
- azure-github/templates/workload-cluster/30-external-dns.yaml
- azure-github/templates/workload-cluster/30-external-secrets-operator.yaml
- azure-github/templates/workload-cluster/30-ingress-nginx.yaml
- azure-github/templates/workload-cluster/30-reloader.yaml
- azure-github/templates/workload-cluster/40-cloudflare-origin-issuer-crd.yaml
- azure-github/templates/workload-cluster/40-clusterissuers.yaml
- azure-github/templates/workload-cluster/40-clustersecretstore.yaml
- azure-github/templates/workload-cluster/41-cloudflare-origin-ca-issuer.yaml
- azure-github/templates/workload-cluster/45-cloudflare-origin-issuer.yaml
- azure-github/templates/workload-cluster/45-environment.yaml
- azure-github/templates/workload-cluster/appproject-workload-cluster.yaml
- azure-github/templates/workload-cluster/cert-issuers/clusterissuers.yaml
- azure-github/templates/workload-cluster/cluster-secret-store/clustersecretstore.yaml
- azure-github/templates/workload-cluster/infrastructure/wait.yaml
- azure-github/templates/workload-cluster/infrastructure/workspace.yaml
- azure-github/templates/workload-cluster/provider-config/providerconfig.yaml
- azure-github/templates/workload-cluster/registry-workload-cluster.yaml
- azure-github/templates/workload-cluster/workload-cluster-environment/metaphor.yaml
- azure-github/terraform/azure/cluster.tf
- azure-github/terraform/azure/main.tf
- azure-github/terraform/azure/modules/workload-cluster/cluster.tf
- azure-github/terraform/azure/modules/workload-cluster/main.tf
- azure-github/terraform/azure/modules/workload-cluster/network.tf
- azure-github/terraform/azure/modules/workload-cluster/secrets.tf
- azure-github/terraform/azure/modules/workload-cluster/variables.tf
Create physical clusters for Azure GitHub
Fixes #
Build an Azure cluster pointing to this branch in the GitOps templates. Until the console work is done, this will require manually adding the `gitops` repo:
1. Copy `templates/workload-cluster` to `registry/<cluster-name>`
2. Move `registry/<cluster-name>/appproject-workload-cluster.yaml` to `registry/clusters/<mgmt>/components/argocd-appprojects`
3. Move `registry/<cluster-name>/registry-workload-cluster.yaml` to `registry/clusters/<mgmt>`
4. Search and replace the following values:
- `<WORKLOAD_CLUSTER_NAME>`: `<cluster-name>`
- `<WORKLOAD_CLUSTER_REGION>`: `ukwest`
- `<WORKLOAD_NODE_COUNT>`: `3`
- `<WORKLOAD_NODE_TYPE>`: `Standard_D2s_v4`
- `<WORKLOAD_EXTERNAL_DNS_DOMAIN_NAME>`: `<domain name>` (see …
> Build real clusters in Azure GitHub

- k3d-github/cluster-types/mgmt/components/kubefirst/console.yaml
- k3d-gitlab/cluster-types/mgmt/components/kubefirst/console.yaml
- Adds k3d env var for kubefirst pro ui
> feat: k3d env var

- metaphor/charts/metaphor/templates/origin-issuer.yaml
- metaphor/charts/metaphor/values.yaml
Add OriginIssure resource for metaphor to utilize cloudflare origin issuer if enabled.
> feat: add originissuer for Metaphor

- aws-github/terraform/aws/eks/main.tf
- aws-gitlab/terraform/aws/eks/main.tf
encode the policy instead of decode which otherwise will throw error while provisioning 😄
> fix: encode instead of decode

- aws-github/terraform/aws/eks/main.tf
- aws-gitlab/terraform/aws/eks/main.tf
Add a suffix to policy name with cluster name in order to avoid `Entity already exists error` :)
> fix: add unique policy name

- google-github/templates/workload-cluster/20-argocd-connection.yaml
- google-github/templates/workload-cluster/infrastructure/workspace.yaml
- google-github/templates/workload-cluster/provider-config/providerconfig.yaml
Updates to get a successfull provisioning of workload cluster
provision a mgmt cluster and then provision and workload cluster ,i already have testing cluster [here](https://kubefirst.kubefirst.tech/dashboard/clusters)
> fix: infrastructure provisioning

- akamai-github/templates/workload-cluster/45-environment.yaml
- akamai-github/templates/workload-cluster/workload-cluster-environment/metaphor.yaml
- akamai-github/templates/workload-vcluster/45-environment.yaml
- azure-github/templates/workload-cluster/45-environment.yaml
- azure-github/templates/workload-cluster/workload-cluster-environment/metaphor.yaml
- azure-github/templates/workload-vcluster/45-environment.yaml
- azure-gitlab/templates/workload-cluster/45-environment.yaml
- azure-gitlab/templates/workload-vcluster/45-environment.yaml
- civo-github/templates/gpu-cluster/45-environment.yaml
- civo-github/templates/gpu-cluster/workload-cluster-environment/metaphor.yaml
- civo-github/templates/workload-cluster/45-environment.yaml
- civo-github/templates/workload-cluster/workload-cluster-environment/metaphor.yaml
- civo-github/templates/workload-vcluster/45-environment.yaml
- civo-gitlab/templates/gpu-cluster/45-environment.yaml
- civo-gitlab/templates/gpu-cluster/workload-cluster-environment/metaphor.yaml
- civo-gitlab/templates/workload-cluster/45-environment.yaml
- civo-gitlab/templates/workload-vcluster/45-environment.yaml
- digitalocean-github/templates/workload-cluster/45-environment.yaml
- digitalocean-gitlab/templates/workload-cluster/45-environment.yaml
- vultr-github/templates/gpu-cluster/45-environment.yaml
- vultr-github/templates/gpu-cluster/workload-cluster-environment/metaphor.yaml
- vultr-github/templates/workload-cluster/45-environment.yaml
- vultr-github/templates/workload-cluster/workload-cluster-environment/metaphor.yaml
add correct token value when detokenising environment while provisioning workload cluster
> fix: add correct environment for detokenising

- akamai-github/templates/workload-cluster/20-argocd-connection.yaml
- akamai-github/templates/workload-cluster/infrastructure/workspace.yaml
- akamai-github/templates/workload-cluster/provider-config/providerconfig.yaml
- akamai-github/terraform/akamai/main.tf
Add physical support for akamai
provision an akamai mgmt cluster using flag `--gitops-template-branch akamai-physical` and provision a workload physical cluster
```bash
go run . akamai create \
--alerts-email xxx \
--github-org xxx \
--dns-provider cloudflare \
--domain-name xxx \
--subdomain akamai.kubefirst \
--cluster-name sje-akamai \
--gitops-template-branch akamai-physical
```
> feat:akamai physical

- civo-github/templates/gpu-cluster/provider-config/providerconfig.yaml
- civo-github/terraform/civo/modules/workload-cluster/main.tf
- civo-gitlab/templates/gpu-cluster/provider-config/providerconfig.yaml
- civo-gitlab/terraform/civo/modules/workload-cluster/main.tf
Fix the talos versioning for GPU provisioning
related to [this](https://github.com/civo/terraform-provider-civo/pull/367).
Provision Civo mgmt cluster and provision a GPU workload
> fix: gpu versioning

- k3d-github/ci/.github/workflows/main.yaml
- k3d-gitlab/ci/.gitlab-ci.yml
- metaphor/.github/workflows/main.yaml
- metaphor/.gitlab-ci.yml
> repo reference update

- aws-github/templates/mgmt/components/crossplane/provider/controllerconfig.yaml
- aws-github/templates/mgmt/components/crossplane/provider/terraform-provider.yaml
- aws-github/templates/workload-host-vcluster/0-providerconfig.yaml
- aws-github/templates/workload-host-vcluster/10-infrastructure.yaml
- aws-github/templates/workload-host-vcluster/15-bootstrap.yaml
- aws-github/templates/workload-host-vcluster/20-argocd-connection.yaml
- aws-github/templates/workload-host-vcluster/30-cert-manager.yaml
- aws-github/templates/workload-host-vcluster/30-external-dns.yaml
- aws-github/templates/workload-host-vcluster/30-external-secrets-operator.yaml
- aws-github/templates/workload-host-vcluster/30-ingress-nginx.yaml
- aws-github/templates/workload-host-vcluster/30-reloader.yaml
- aws-github/templates/workload-host-vcluster/40-clusterissuers.yaml
- aws-github/templates/workload-host-vcluster/40-clustersecretstore.yaml
- aws-github/templates/workload-host-vcluster/45-environment.yaml
- aws-github/templates/workload-host-vcluster/appproject-workload-cluster.yaml
- aws-github/templates/workload-host-vcluster/bootstrap/workspace.yaml
- aws-github/templates/workload-host-vcluster/cert-issuers/clusterissuers.yaml
- aws-github/templates/workload-host-vcluster/cluster-secret-store/clustersecretstore.yaml
- aws-github/templates/workload-host-vcluster/infrastructure/wait.yaml
- aws-github/templates/workload-host-vcluster/infrastructure/workspace.yaml
- aws-github/templates/workload-host-vcluster/kubefirst.yaml
- aws-github/templates/workload-host-vcluster/provider-config/providerconfig.yaml
- aws-github/templates/workload-host-vcluster/registry-workload-cluster.yaml
- aws-github/terraform/aws/modules/workload-vcluster/main.tf
- aws-github/terraform/aws/modules/workload-vcluster/values.yaml
- aws-github/terraform/aws/modules/workload-vcluster/variables.tf
- aws-gitlab/templates/mgmt/components/crossplane/provider/controllerconfig.yaml
- aws-gitlab/templates/mgmt/components/crossplane/provider/terraform-provider.yaml
> feat: add host vcluster

- aws-github/templates/workload-host-vcluster/10-infrastructure.yaml
- aws-github/templates/workload-host-vcluster/infrastructure/wait.yaml
- aws-github/templates/workload-host-vcluster/registry-workload-cluster.yaml
> remove bitname
